name: New feature
description: Begin tracking new product features with an issue
title: "[Feature]: "
labels: ["feature"]
projects: ["platformsh/projects/3"]
assignees:
  - chadwcarlson
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping us document new features!
  - type: dropdown
    id: offer
    validations:
      required: true
    attributes:
      label: Offer
      multiple: true
      description: What product is impacted by the feature? (select all that apply)
      options:
        - Platform.sh
        - Upsun
        - Blackfire.io
        - DDEV
      default: 0
  # - type: input
  #   id: contact
  #   attributes:
  #     label: Contact Details
  #     description: How can we get in touch with you if we need more info?
  #     placeholder: ex. email@example.com
  #   validations:
  #     required: false
  # - type: textarea
  #   id: what-happened
  #   attributes:
  #     label: What happened?
  #     description: Also tell us, what did you expect to happen?
  #     placeholder: Tell us what you see!
  #     value: "A bug happened!"
  #   validations:
  #     required: true
  # - type: dropdown
  #   id: version
  #   attributes:
  #     label: Version
  #     description: What version of our software are you running?
  #     options:
  #       - 1.0.2 (Default)
  #       - 1.0.3 (Edge)
  #     default: 0
  #   validations:
  #     required: true
  # - type: dropdown
  #   id: browsers
  #   attributes:
  #     label: What browsers are you seeing the problem on?
  #     multiple: true
  #     options:
  #       - Firefox
  #       - Chrome
  #       - Safari
  #       - Microsoft Edge
  - type: textarea
    id: description
    attributes:
      label: Feature details
      description: Please any details/descriptions that can be shared publicly at this point. The DevRel team will follow-up in our first sync to detail the issue for delivery.
      placeholder: |

        ## Overview

        At the very least, please edit this line with a few sentences publicly describing the feature here. 

        ## Affected docs pages

        TBD

        ## Other details

        TBD

        
        
  # - type: checkboxes
  #   id: terms
  #   attributes:
  #     label: Code of Conduct
  #     description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com)
  #     options:
  #       - label: I agree to follow this project's Code of Conduct
  #         required: true
